Basmach_audio = [('https://drive.google.com/file/d/1qa8IB7hBiVbINWSRmcLXpuTBR-IXJhYM/view?usp=share_link', 'audio'),
                 ('https://drive.google.com/file/d/1NwW1JiDsznF-OQZNBe43TiOYW8qdASH2/view?usp=share_link', 'photo',
                  'Портрет А.Б. Куракина',
                  'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D1%80%D0%B0%D0%BA%D0%B8%D0%BD,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%91%D0%BE%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B8%D1%87'),

                 ('https://drive.google.com/file/d/1KB3k4FspkDnMULwuuQWdmiqYuUyziHXl/view?usp=share_link', 'audio'),
                 ('https://drive.google.com/file/d/1ayfl4FnZ_mQj0Xf-mCQHw9Qfw8DtKiTc/view?usp=share_link', 'photo',
                  'Портрет Огюста Фредерика Луи Виесс де Мармона',
                  'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%80%D0%BC%D0%BE%D0%BD,_%D0%9E%D0%B3%D1%8E%D1%81%D1%82_%D0%A4%D1%80%D0%B5%D0%B4%D0%B5%D1%80%D0%B8%D0%BA_%D0%9B%D1%83%D0%B8'),

                 ('https://drive.google.com/file/d/14r61xWHHMHBwQvjzo_GKpGTW3isyHhBE/view?usp=share_link', 'photo',
                  'Фасад дома А.Б. Куракина'),
                 ('https://drive.google.com/file/d/104XuUD_oJQrANjn2OhUs0a0lc93Iz3So/view?usp=share_link', 'audio'),
                 ('https://drive.google.com/file/d/1OGIRsH7uvRnv7SZUoDtpRIlfYfyPxXwe/view?usp=share_link', 'audio'),
                 ('https://drive.google.com/file/d/1qf7ayATPpLsYN4tROflQyLShWuoK5RPa/view?usp=share_link', 'photo',
                  'Преподавательский состав Александровского коммерческого училища'),
                 ('https://drive.google.com/file/d/1OWSrGbQ8m0bO8zhmUIurjVl1RxTiVvOY/view?usp=share_link', 'photo',
                  'Фасад Московского института химического машиностроения'),
                 ('https://drive.google.com/file/d/1XLoWn2NAdmpkbww5rYr7VxfN5SPysey7/view?usp=share_link', 'photo',
                  'Мемориал Леониду Костандову',
                  'https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%BE%D0%B2,_%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%90%D1%80%D0%BA%D0%B0%D0%B4%D1%8C%D0%B5%D0%B2%D0%B8%D1%87'),

                 ('https://drive.google.com/file/d/14XBFEVadlhk9nVHW7cnhUBnUfDAq8HVP/view?usp=share_link', 'photo',
                  "Памятник Катюше",
                  'https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%82%D1%8E%D1%88%D0%B0_(%D0%BF%D1%80%D0%BE%D0%B7%D0%B2%D0%B8%D1%89%D0%B5_%D0%BE%D1%80%D1%83%D0%B6%D0%B8%D1%8F)'),

                 ('https://drive.google.com/file/d/1jBeiZplzyDAEo7W_nE2630C8qTp0sNr-/view?usp=share_link', 'audio'),
                 ('https://drive.google.com/file/d/1YkZ08NwYMnnpXh_U2qV8mITAkPcoBp2a/view?usp=share_link', 'photo',
                  'Фото здания после пожара 1990 года'),
                 ('https://drive.google.com/file/d/1DksrY4c5VBlvu3_1UyUmCz_AHTy8kkw1/view?usp=share_link', 'audio'),
                 ('https://drive.google.com/file/d/1VvnLTvwpvb9-zh69DwfWA72Rk30PY8dG/view?usp=share_link', 'photo',
                  'Фасад современного здания ВШЭ'),
                 ]

Basmach_text = [('https://drive.google.com/file/d/1Aoidb81XaSeBnoDpcUGbt37wWHKn196k/view?usp=share_link', 'text'),
                0,
                ('https://drive.google.com/file/d/1NwW1JiDsznF-OQZNBe43TiOYW8qdASH2/view?usp=share_link', 'photo',
                 'Портрет самого А.Б. Куракина',
                 'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D1%80%D0%B0%D0%BA%D0%B8%D0%BD,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%91%D0%BE%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%B8%D1%87'),

                1,
                ('https://drive.google.com/file/d/1ayfl4FnZ_mQj0Xf-mCQHw9Qfw8DtKiTc/view?usp=share_link', 'photo',
                 'Портрет Огюста Фредерика Луи Виесс де Мармона',
                 'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%80%D0%BC%D0%BE%D0%BD,_%D0%9E%D0%B3%D1%8E%D1%81%D1%82_%D0%A4%D1%80%D0%B5%D0%B4%D0%B5%D1%80%D0%B8%D0%BA_%D0%9B%D1%83%D0%B8'),

                ('https://drive.google.com/file/d/14r61xWHHMHBwQvjzo_GKpGTW3isyHhBE/view?usp=share_link', 'photo',
                 'Фасад дома А.Б. Куракина'),
                2,

                ('https://drive.google.com/file/d/1qf7ayATPpLsYN4tROflQyLShWuoK5RPa/view?usp=share_link', 'photo',
                 'Преподавательский состав Александровского коммерческого училища'),
                3,
                ('https://drive.google.com/file/d/1OWSrGbQ8m0bO8zhmUIurjVl1RxTiVvOY/view?usp=share_link', 'photo',
                 'Фасад Московского института химического машиностроения'),
                4,
                ('https://drive.google.com/file/d/1XLoWn2NAdmpkbww5rYr7VxfN5SPysey7/view?usp=share_link', 'photo',
                 'Мемориал Леониду Костандову',
                 'https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%BE%D0%B2,_%D0%9B%D0%B5%D0%BE%D0%BD%D0%B8%D0%B4_%D0%90%D1%80%D0%BA%D0%B0%D0%B4%D1%8C%D0%B5%D0%B2%D0%B8%D1%87'),

                5,
                ('https://drive.google.com/file/d/14XBFEVadlhk9nVHW7cnhUBnUfDAq8HVP/view?usp=share_link', 'photo',
                 "Памятник Катюше",
                 'https://ru.wikipedia.org/wiki/%D0%9A%D0%B0%D1%82%D1%8E%D1%88%D0%B0_(%D0%BF%D1%80%D0%BE%D0%B7%D0%B2%D0%B8%D1%89%D0%B5_%D0%BE%D1%80%D1%83%D0%B6%D0%B8%D1%8F)'),
                6,
                ('https://drive.google.com/file/d/1YkZ08NwYMnnpXh_U2qV8mITAkPcoBp2a/view?usp=share_link', 'photo',
                 'Фото здания после пожара 1990 года'),
                ('https://drive.google.com/file/d/1Px4BSTne-GHTXj7HAixfWwEvFm4-Ie3_/view?usp=share_link', 'photo', ''),
                7,
                ('https://drive.google.com/file/d/1VvnLTvwpvb9-zh69DwfWA72Rk30PY8dG/view?usp=share_link', 'photo',
                 'Фасад современного здания ВШЭ'),
                ]

Myasnickaya_text = [('https://drive.google.com/file/d/1Js5T09h3Muc94kSL0lKCDJdYdUYCtZm7/view?usp=sharing', 'text'),
                    0,
                    ('https://drive.google.com/file/d/1lJpeLxjnT6Ae3mi6PQF364pKyqtGgKRk/view?usp=share_link', 'photo',
                     'Герб князя Якова Ивановича Кольцово-Мосальского',
                     'https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BB%D1%8C%D1%86%D0%BE%D0%B2%D1%8B-%D0%9C%D0%BE%D1%81%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B5'),

                    1,
                    ('https://drive.google.com/file/d/1ac6y5NBh7XfOIPW-YIAYoVErYFkvYQXA/view?usp=share_link', 'photo',
                     'Фото Ованеса Ананьяна (Ивана Степановича Ананова)'),
                    2,
                    ('https://drive.google.com/file/d/1xnNLjB7DofnHeN77q-Rtjxg8icuwFJfk/view?usp=share_link', 'photo',
                     'Мозаика на полу центрального хола Фирмы Мюр и Мерлиз',
                     'https://ru.wikipedia.org/wiki/%D0%9C%D1%8E%D1%80_%D0%B8_%D0%9C%D0%B5%D1%80%D0%B8%D0%BB%D0%B8%D0%B7'),

                    3,
                    ('https://drive.google.com/file/d/1K3AOGeeGMoG_8YeqdNiE0_UqRKXBib3i/view?usp=share_link', 'photo',
                     'Октябрьская революция, одним из ключевых эпизодов которой стала всеобщая политическая забастовка 6 декабря в здании на Мясницкой',
                     'https://ru.wikipedia.org/wiki/%D0%9E%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B5%D0%B2%D0%BE%D0%BB%D1%8E%D1%86%D0%B8%D1%8F'),
                    4,
                    ('https://drive.google.com/file/d/1FDrq78QgqzuHS9GLQMJm16RGog2WBy9h/view?usp=share_link', 'photo',
                     'Фото инженера и предпринимателя Александра Вениаминовича Бари',
                     'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D0%B8,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%92%D0%B5%D0%BD%D0%B8%D0%B0%D0%BC%D0%B8%D0%BD%D0%BE%D0%B2%D0%B8%D1%87'),

                    5,
                    ('https://drive.google.com/file/d/14m-J2vHqz2O97SNG-rFGHRZAQ4O6g43c/view?usp=share_link', 'photo',
                     'Фото Владимира Григорьевича Шухова',
                     'https://ru.wikipedia.org/wiki/%D0%A8%D1%83%D1%85%D0%BE%D0%B2,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87'),

                    6,
                    ('https://drive.google.com/file/d/1aD7UGPvYfUpiSDbU9m7aWKsQg5vUfkKa/view?usp=share_link', 'photo',
                     'Башня на Шаболовке - одна из самых известных построект В. Г. Шухова'),
                    7,
                    ('https://drive.google.com/file/d/1fEhamyu2KMEuOFtXARnstuUOqDiTwVHf/view?usp=share_link', 'photo',
                     'Фасад современного здания на Мясницкой'),
                    ]

Myasnickaya_audio = [('https://drive.google.com/file/d/1eabxqMf4d_Sk-HdIZ7Cj3PvqRIR5BF9q/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1lJpeLxjnT6Ae3mi6PQF364pKyqtGgKRk/view?usp=share_link', 'photo',
                      'Герб князя Якова Ивановича Кольцово-Мосальского',
                      'https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BB%D1%8C%D1%86%D0%BE%D0%B2%D1%8B-%D0%9C%D0%BE%D1%81%D0%B0%D0%BB%D1%8C%D1%81%D0%BA%D0%B8%D0%B5'),

                     ('https://drive.google.com/file/d/1iRd5bRP2I3vYK2Ni1bHsqYGwYXRzTkQu/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1ac6y5NBh7XfOIPW-YIAYoVErYFkvYQXA/view?usp=share_link', 'photo',
                      'Фото Ованеса Ананьяна (Ивана Степановича Ананова)'),
                     ('https://drive.google.com/file/d/15sEBuJ5wA2fQcSx9Pzqxf4Q8U93Cd_pE/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1xnNLjB7DofnHeN77q-Rtjxg8icuwFJfk/view?usp=share_link', 'photo',
                      'Мозаика на полу центрального хола Фирмы Мюр и Мерлиз',
                      'https://ru.wikipedia.org/wiki/%D0%9C%D1%8E%D1%80_%D0%B8_%D0%9C%D0%B5%D1%80%D0%B8%D0%BB%D0%B8%D0%B7'),

                     ('https://drive.google.com/file/d/1UkRsvV51aewOPNwBQuqtFUeGILeCutV-/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1K3AOGeeGMoG_8YeqdNiE0_UqRKXBib3i/view?usp=share_link', 'photo',
                      'Октябрьская революция, одним из ключевых эпизодов которой стала всеобщая политическая забастовка 6 декабря в здании на Мясницкой',
                      'https://ru.wikipedia.org/wiki/%D0%9E%D0%BA%D1%82%D1%8F%D0%B1%D1%80%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D1%80%D0%B5%D0%B2%D0%BE%D0%BB%D1%8E%D1%86%D0%B8%D1%8F'),

                     ('https://drive.google.com/file/d/1s4wTDJ0Xa1i01yyYHjj9OHBPMMEX5OaT/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1FDrq78QgqzuHS9GLQMJm16RGog2WBy9h/view?usp=share_link', 'photo',
                      'Фото инженера и предпринимателя Александра Вениаминовича Бари',
                      'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D0%B8,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%92%D0%B5%D0%BD%D0%B8%D0%B0%D0%BC%D0%B8%D0%BD%D0%BE%D0%B2%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/1wYsm6JH1PBCrvnFPrX7rzlJCQvKsFZfc/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/14m-J2vHqz2O97SNG-rFGHRZAQ4O6g43c/view?usp=share_link', 'photo',
                      'Фото Владимира Григорьевича Шухова',
                      'https://ru.wikipedia.org/wiki/%D0%A8%D1%83%D1%85%D0%BE%D0%B2,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%93%D1%80%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/170ToG-KywLxywsE92SXCOSAutvlc5Lrk/view?usp=share_link', 'auido'),
                     ('https://drive.google.com/file/d/1aD7UGPvYfUpiSDbU9m7aWKsQg5vUfkKa/view?usp=share_link', 'photo',
                      'Башня на Шаболовке - одна из самых известных построект В. Г. Шухова'),
                     ('https://drive.google.com/file/d/18VzTbezDxeEdwv-Xyk0PNFQBxDPTd-Ee/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1fEhamyu2KMEuOFtXARnstuUOqDiTwVHf/view?usp=share_link', 'photo',
                      'Фасад современного здания на Мясницкой')]

M_Trehsvyat_text = [('https://drive.google.com/file/d/1MHBw7p78MoLQpamwdEaSAUDwAppdpFx3/view?usp=share_link', 'text'),
                    0,
                    ('https://drive.google.com/file/d/1V-5Pg34Pltsj51wCsceElhrNJbK5s0tS/view?usp=share_link', 'photo',
                     'Портрет Екатерины Великой',
                     'https://ru.wikipedia.org/wiki/%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B0_II'),
                    1,
                    ('https://drive.google.com/file/d/1IXt9fEFrVn1CnvslXOk8jHc-8sl6Ro6f/view?usp=share_link', 'photo',
                     'Портрет Федора Андреевича Остермана',
                     'https://ru.wikipedia.org/wiki/%D0%9E%D1%81%D1%82%D0%B5%D1%80%D0%BC%D0%B0%D0%BD,_%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2%D0%B8%D1%87'),
                    2,
                    ('https://drive.google.com/file/d/14cuHenlrTqhDHatARq5Oo2v-QavC1EWw/view?usp=share_link', 'photo',
                     'Портрет Федора Тютчева в детстве'),
                    ('https://drive.google.com/file/d/1G3w4xaKiOvcfxG5ZXSTZ4vvq8-ipK-as/view?usp=share_link', 'photo',
                     'Портрет взрослого Федора Тютчева',
                     'https://ru.wikipedia.org/wiki/%D0%A2%D1%8E%D1%82%D1%87%D0%B5%D0%B2,_%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87'),
                    3,
                    ('https://drive.google.com/file/d/1w_wA8dRbDVvZ11yuHnSxnsnjrki4AAvu/view?usp=share_link', 'photo',
                     '"Пожар Москвы 1812 года". \n Автор картины И. К. Айвазовский',
                     'https://ru.wikipedia.org/wiki/%D0%90%D0%B9%D0%B2%D0%B0%D0%B7%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD%D0%BE%D0%B2%D0%B8%D1%87'),
                    4,
                    ('https://drive.google.com/file/d/1IbBEVgps-8qRDGgkQSWYevZANilERflw/view?usp=share_link', 'photo',
                     'Полицейская и пожарные части с каланчой'),
                    5,
                    ('https://drive.google.com/file/d/1G-_OALqkOOXqxGxoEtJWSEIFobnXawOR/view?usp=share_link', 'photo',
                     'Конный выезд пожарной бригады'),
                    6,
                    ('https://drive.google.com/file/d/18UVJFXizuHVCb73X8dw74s-67dybIh88/view?usp=sharing', 'photo',
                     'Владмир Владимирович Маяковский',
                     'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%8F%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87'),
                    7,
                    ('https://drive.google.com/file/d/18Ygxn0paecsx3zf5cWj-w0eMwE-b-lUP/view?usp=share_link', 'photo',
                     'Портрет Софьи Петровны Кувшинниковой',
                     'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%B2%D1%88%D0%B8%D0%BD%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0,_%D0%A1%D0%BE%D1%84%D1%8C%D1%8F_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%BD%D0%B0'),
                    8,
                    ('https://drive.google.com/file/d/11YTE3MYAKD76pu8TuJ3k-H85P_cNPYcl/view?usp=share_link', 'photo',
                     'Картина "Охотники на привале".\nАвтор В.Г. Перов',
                     'https://ru.wikipedia.org/wiki/%D0%9E%D1%85%D0%BE%D1%82%D0%BD%D0%B8%D0%BA%D0%B8_%D0%BD%D0%B0_%D0%BF%D1%80%D0%B8%D0%B2%D0%B0%D0%BB%D0%B5'),
                    9,
                    ('https://drive.google.com/file/d/1s1l5tOwlO8cmLBeFHZAJZ3Ehjlmv3YZi/view?usp=share_link', 'photo',
                     'Куйбышева',
                     'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%B9%D0%B1%D1%8B%D1%88%D0%B5%D0%B2,_%D0%92%D0%B0%D0%BB%D0%B5%D1%80%D0%B8%D0%B0%D0%BD_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87'),

                    10,
                    ('https://drive.google.com/file/d/1mTpext-T_SeQEG-re2ebTwIAJvYCulnc/view?usp=sharing', 'photo',
                     'Корпус в Хитровском переулке в наши дни'),
                    ]

M_Trehsvyat_audio = [('https://drive.google.com/file/d/182FS_CTpGMzMSC3jdbVpFfxZ9mbec4Mt/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1V-5Pg34Pltsj51wCsceElhrNJbK5s0tS/view?usp=share_link', 'photo',
                      'Портрет Екатерины Великой',
                      'https://ru.wikipedia.org/wiki/%D0%95%D0%BA%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B0_II'),

                     ('https://drive.google.com/file/d/1IBZEhnxdxkcy84mNT3cZaIE9wiHMwPi5/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1IXt9fEFrVn1CnvslXOk8jHc-8sl6Ro6f/view?usp=share_link', 'photo',
                      'Портрет Федора Андреевича Остермана',
                      'https://ru.wikipedia.org/wiki/%D0%9E%D1%81%D1%82%D0%B5%D1%80%D0%BC%D0%B0%D0%BD,_%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/1ejQbClFdatFFUWvIqUpUmWr1vanBtt82/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/14cuHenlrTqhDHatARq5Oo2v-QavC1EWw/view?usp=share_link', 'photo',
                      'Портрет Федора Тютчева в детстве'),
                     ('https://drive.google.com/file/d/1G3w4xaKiOvcfxG5ZXSTZ4vvq8-ipK-as/view?usp=share_link', 'photo',
                      'Портрет взрослого Федора Тютчева',
                      'https://ru.wikipedia.org/wiki/%D0%A2%D1%8E%D1%82%D1%87%D0%B5%D0%B2,_%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/1Ab_SinaJo85eBA7uadNXASwDMADV2i7g/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1w_wA8dRbDVvZ11yuHnSxnsnjrki4AAvu/view?usp=share_link', 'photo',
                      '"Пожар Москвы 1812 года". \n Автор картины И. К. Айвазовский',
                      'https://ru.wikipedia.org/wiki/%D0%90%D0%B9%D0%B2%D0%B0%D0%B7%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%98%D0%B2%D0%B0%D0%BD_%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B0%D0%BD%D1%82%D0%B8%D0%BD%D0%BE%D0%B2%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/1t7Z2UjcZp29GNK7Ak-oSyQuxOUIobMfK/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1IbBEVgps-8qRDGgkQSWYevZANilERflw/view?usp=share_link', 'photo',
                      'Полицейская и пожарные части с каланчой'),
                     ('https://drive.google.com/file/d/175VmgqNWUsHLnRvwLaUkIla7u7glZRYZ/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1G-_OALqkOOXqxGxoEtJWSEIFobnXawOR/view?usp=share_link', 'photo',
                      'Конный выезд пожарной бригады'),
                     ('https://drive.google.com/file/d/1dtATV02IdFY6pveB2RvhBQ-ClYfi_JU-/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/18UVJFXizuHVCb73X8dw74s-67dybIh88/view?usp=sharing', 'photo',
                      'Владмир Владимирович Маяковский',
                      'https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%8F%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B9,_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/1eNefOtvtMdHKh90GKCiaXfnHlXxSPMMU/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/18Ygxn0paecsx3zf5cWj-w0eMwE-b-lUP/view?usp=share_link', 'photo',
                      'Портрет Софьи Петровны Кувшинниковой',
                      'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%B2%D1%88%D0%B8%D0%BD%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2%D0%B0,_%D0%A1%D0%BE%D1%84%D1%8C%D1%8F_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%BD%D0%B0'),

                     ('https://drive.google.com/file/d/11YTE3MYAKD76pu8TuJ3k-H85P_cNPYcl/view?usp=share_link', 'photo',
                      'Картина "Охотники на привале".\nАвтор В.Г. Перов',
                      'https://ru.wikipedia.org/wiki/%D0%9E%D1%85%D0%BE%D1%82%D0%BD%D0%B8%D0%BA%D0%B8_%D0%BD%D0%B0_%D0%BF%D1%80%D0%B8%D0%B2%D0%B0%D0%BB%D0%B5'),

                     ('https://drive.google.com/file/d/1A0eV4z-UmDLqdKwzWy2wN0IZBpmi7YiD/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1s1l5tOwlO8cmLBeFHZAJZ3Ehjlmv3YZi/view?usp=share_link', 'photo',
                      'Куйбышева',
                      'https://ru.wikipedia.org/wiki/%D0%9A%D1%83%D0%B9%D0%B1%D1%8B%D1%88%D0%B5%D0%B2,_%D0%92%D0%B0%D0%BB%D0%B5%D1%80%D0%B8%D0%B0%D0%BD_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/1mTWmdwsRji13MPxWRhBZ53RgAze-Un3Q/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1mTpext-T_SeQEG-re2ebTwIAJvYCulnc/view?usp=sharing', 'photo',
                      'Корпус в Хитровском переулке в наши дни'),
                     ]

B_Trehsvyat_text = [('https://drive.google.com/file/d/13AkaOl8vJm5M84MxKw8iXW5KfeEbRiYS/view?usp=sharing', 'text'),
                    0,
                    ('https://drive.google.com/file/d/1hywvyZ4sEDFZztmvkwUxelac6eE28uPn/view?usp=share_link', 'photo',
                     'Фото М.Ф. Морозовой',
                     'https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BE%D0%B2%D0%B0,_%D0%9C%D0%B0%D1%80%D0%B8%D1%8F_%D0%A4%D1%91%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D0%BD%D0%B0'),

                    ('https://drive.google.com/file/d/1YYimKXXxPAATczYxn5cXGi-b_hY8PGtx/view?usp=share_link', 'photo',
                     'Фото С.Т. Морозового',
                     'https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BE%D0%B2,_%D0%A1%D0%B0%D0%B2%D0%B2%D0%B0_%D0%A2%D0%B8%D0%BC%D0%BE%D1%84%D0%B5%D0%B5%D0%B2%D0%B8%D1%87'),

                    1,
                    ('https://drive.google.com/file/d/1GnvezHY8Mtr421EjSXfb4hbZoos51lAw/view?usp=share_link', 'photo',
                     'Портрет И. И. Левитана',
                     'https://ru.wikipedia.org/wiki/%D0%9B%D0%B5%D0%B2%D0%B8%D1%82%D0%B0%D0%BD,_%D0%98%D1%81%D0%B0%D0%B0%D0%BA_%D0%98%D0%BB%D1%8C%D0%B8%D1%87'),

                    ('https://drive.google.com/file/d/1wlGSc_1QFSyWZ7IidUrV-LmK7nm4gjEA/view?usp=sharing', 'photo',
                     'Одна из самых известных работ И.И. Левитана',
                     'https://ru.wikipedia.org/wiki/%D0%97%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F_%D0%BE%D1%81%D0%B5%D0%BD%D1%8C_(%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%B0_%D0%9B%D0%B5%D0%B2%D0%B8%D1%82%D0%B0%D0%BD%D0%B0)'),

                    ('https://drive.google.com/file/d/1ik0ZR_XTQad63kVgdoI0MRM3QW9n_ulh/view?usp=share_link', 'photo',
                     'Мастерская И. И. Левитана'),
                    2,
                    ('https://drive.google.com/file/d/141vxG9VkHW226KI6s2YhE5aH8E1-OKev/view?usp=share_link', 'photo',
                     'Штаб левых эссеров'),
                    3,
                    ('https://drive.google.com/file/d/1jAHnNW0ob1s1TWADTX0_JFx544CZj63W/view?usp=share_link', 'photo',
                     'Университет МИЭМ'),
                    ('https://drive.google.com/file/d/1ZSlx5Hdl9grZdKETeAspi3s2cI9kvGbN/view?usp=share_link', 'photo',
                     ''),
                    4,
                    ('https://drive.google.com/file/d/1UXVdxUhtsAmsiwCkt20EmVGp88Xl7wH2/view?usp=share_link', 'photo',
                     'Корпус ВШЭ на Большом Трехсвятительском переулке'),
                    ]

B_Trehsvyat_audio = [('https://drive.google.com/file/d/15yDKWn6PIYYlMo5VvkZWqHsbKvNTi3l6/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1hywvyZ4sEDFZztmvkwUxelac6eE28uPn/view?usp=share_link', 'photo',
                      'Фото М.Ф. Морозовой',
                      'https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BE%D0%B2%D0%B0,_%D0%9C%D0%B0%D1%80%D0%B8%D1%8F_%D0%A4%D1%91%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D0%BD%D0%B0'),

                     ('https://drive.google.com/file/d/1YYimKXXxPAATczYxn5cXGi-b_hY8PGtx/view?usp=share_link', 'photo',
                      'Фото С.Т. Морозового',
                      'https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D1%80%D0%BE%D0%B7%D0%BE%D0%B2,_%D0%A1%D0%B0%D0%B2%D0%B2%D0%B0_%D0%A2%D0%B8%D0%BC%D0%BE%D1%84%D0%B5%D0%B5%D0%B2%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/12lS36HqUeIcYD2mA7g5FG1-1OYy8GQTG/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1GnvezHY8Mtr421EjSXfb4hbZoos51lAw/view?usp=share_link', 'photo',
                      'Портрет И. И. Левитана',
                      'https://ru.wikipedia.org/wiki/%D0%9B%D0%B5%D0%B2%D0%B8%D1%82%D0%B0%D0%BD,_%D0%98%D1%81%D0%B0%D0%B0%D0%BA_%D0%98%D0%BB%D1%8C%D0%B8%D1%87'),

                     ('https://drive.google.com/file/d/1wlGSc_1QFSyWZ7IidUrV-LmK7nm4gjEA/view?usp=sharing', 'photo',
                      'Одна из самых известных работ И.И. Левитана',
                      'https://ru.wikipedia.org/wiki/%D0%97%D0%BE%D0%BB%D0%BE%D1%82%D0%B0%D1%8F_%D0%BE%D1%81%D0%B5%D0%BD%D1%8C_(%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%B0_%D0%9B%D0%B5%D0%B2%D0%B8%D1%82%D0%B0%D0%BD%D0%B0)'),

                     ('https://drive.google.com/file/d/1ik0ZR_XTQad63kVgdoI0MRM3QW9n_ulh/view?usp=share_link', 'photo',
                      'Мастерская И. И. Левитана'),
                     ('https://drive.google.com/file/d/1gjZ8jz1J_cNLk95rYtC2bvHeRetKtpwU/view?usp=share_link', 'audio'),

                     ('https://drive.google.com/file/d/141vxG9VkHW226KI6s2YhE5aH8E1-OKev/view?usp=share_link', 'photo',
                      'Штаб левых эссеров'),
                     ('https://drive.google.com/file/d/16XAa7HreWPgcOvweC4TYkrzC8UjE4b6o/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1RVJLypvtxA1USOacfTLniaLSdywIrAwq/view?usp=share_link', 'audio'),
                     ('https://drive.google.com/file/d/1jAHnNW0ob1s1TWADTX0_JFx544CZj63W/view?usp=share_link', 'photo',
                      'Университет МИЭМ'),
                     ('https://drive.google.com/file/d/1ZSlx5Hdl9grZdKETeAspi3s2cI9kvGbN/view?usp=share_link', 'photo',
                      ''),
                     ('https://drive.google.com/file/d/1UXVdxUhtsAmsiwCkt20EmVGp88Xl7wH2/view?usp=share_link', 'photo',
                      'Корпус ВШЭ на Большом Трехсвятительском переулке'),
                     ]

Pokra_text = [('https://drive.google.com/file/d/1dImUJz56oJPp4WcC5ckVAJgrVwySZCmr/view?usp=share_link', 'text'),
              0,
              ('https://drive.google.com/file/d/1VYOwQQ5TiGy7WlRIdd3aJJCa_H__igeJ/view?usp=share_link', 'photo',
               'Дом Дурасова'),
              1,
              ('https://drive.google.com/file/d/1ZOmFSraZrEDlTQXTNmpLF9vHwIF_EEgc/view?usp=share_link', 'photo',
               'Фото А. И. Абрикосова',
               'https://ru.wikipedia.org/wiki/%D0%90%D0%B1%D1%80%D0%B8%D0%BA%D0%BE%D1%81%D0%BE%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87_(%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D1%82%D0%B5%D0%BB%D1%8C)'),

              ('https://drive.google.com/file/d/1r7MbxpLy_fnIC34_JTzrv22VFOF8EkOB/view?usp=share_link', 'photo',
               'Концерн Бабаевский',
               'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B1%D0%B0%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9_(%D0%BA%D0%BE%D0%BD%D1%86%D0%B5%D1%80%D0%BD)'),

              2,
              ('https://drive.google.com/file/d/1jqUyas22Nw63BmDJDAzhNnc68xhpc44Q/view?usp=share_link', 'photo',
               'Тот самый дом с гипсовыми статуями'),
              3,
              ('https://drive.google.com/file/d/1d45hWyfaqmhpTj5w4muY9_bnAdWOc9KD/view?usp=share_link', 'photo',
               'Фото корпуса ВШЭ на Покровском бульваре'),
              ('https://drive.google.com/file/d/1hQEFBMdQqYr5b0l9Y-8DRqlVAmhHOJEM/view?usp=share_link', 'photo',
               'Фото корпуса изнутри')
              ]

Pokra_audio = [('https://drive.google.com/file/d/1H42sztPahDM-S_-_yiEWFyvTt7f94HYQ/view?usp=share_link', 'audio'),
               ('https://drive.google.com/file/d/1VYOwQQ5TiGy7WlRIdd3aJJCa_H__igeJ/view?usp=share_link', 'photo',
                'Дом Дурасова'),
               ('https://drive.google.com/file/d/1sK8SFl_IJoGfqRERMeNU72nWcjvLxUGE/view?usp=share_link', 'audio'),
               ('https://drive.google.com/file/d/1ZOmFSraZrEDlTQXTNmpLF9vHwIF_EEgc/view?usp=share_link', 'photo',
                'Фото А. И. Абрикосова',
                'https://ru.wikipedia.org/wiki/%D0%90%D0%B1%D1%80%D0%B8%D0%BA%D0%BE%D1%81%D0%BE%D0%B2,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9_%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87_(%D0%BF%D1%80%D0%B5%D0%B4%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D1%82%D0%B5%D0%BB%D1%8C)'),

               ('https://drive.google.com/file/d/1r7MbxpLy_fnIC34_JTzrv22VFOF8EkOB/view?usp=share_link', 'photo',
                'Концерн Бабаевский',
                'https://ru.wikipedia.org/wiki/%D0%91%D0%B0%D0%B1%D0%B0%D0%B5%D0%B2%D1%81%D0%BA%D0%B8%D0%B9_(%D0%BA%D0%BE%D0%BD%D1%86%D0%B5%D1%80%D0%BD)'),

               ('https://drive.google.com/file/d/1J7VcIPFU_ps-M47hc8XMVnAQBOM4sgW0/view?usp=share_link', 'audio'),
               ('https://drive.google.com/file/d/1jqUyas22Nw63BmDJDAzhNnc68xhpc44Q/view?usp=share_link', 'photo',
                'Тот самый дом с гипсовыми статуями'),

               ('https://drive.google.com/file/d/1rl_xSTQD_nLDtt9dDUs-r7xHcbbVg-Q_/view?usp=share_link', 'photo',
                'Здание военно-инженерной академии имени Куйбышева '),
               ('https://drive.google.com/file/d/1oDSdEpVRpSKklIe7t1GSshuB1iQ9IcR1/view?usp=share_link', 'audio'),
               ('https://drive.google.com/file/d/1d45hWyfaqmhpTj5w4muY9_bnAdWOc9KD/view?usp=share_link', 'photo',
                'Фото корпуса ВШЭ на Покровском бульваре'),
               ('https://drive.google.com/file/d/1hQEFBMdQqYr5b0l9Y-8DRqlVAmhHOJEM/view?usp=share_link', 'photo',
                'Фото корпуса изнутри')
               ]
